"""
migrate_data_to_crebo — one-shot, idempotent migration that consolidates
the 8-criterion English rubric shape (security / code_quality /
architecture / testing / performance / documentation / validation /
best_practices) into the canonical 6-criterion Crebo 25604 shape
(code_ontwerp / code_kwaliteit / veiligheid / testen / verbetering /
samenwerking).

Companion to migrate_rubrics_to_crebo, which only rewrites
Rubric.criteria. This command does the data side: existing
GradingSession scores, SkillObservations, and SkillMetrics that were
keyed by the 8 English slugs need to be remapped, deduplicated, and
re-bound so the teacher's "Eindniveau" / "Per criterium" widgets and
the student's dashboard show consistent CREBO-aligned data.

Lossy mappings (8 → 6):
    security      -> veiligheid       (1:1, base)
    validation    -> veiligheid       (folded; merged scores averaged)
    code_quality  -> code_kwaliteit   (1:1, base)
    best_practices-> code_kwaliteit   (folded; merged scores averaged)
    architecture  -> code_ontwerp     (1:1)
    testing       -> testen           (1:1)
    performance   -> verbetering      (1:1, base — but combined with docs)
    documentation -> verbetering      (folded; merged scores averaged)

Plus introduces samenwerking with no English equivalent — historical
sessions stay null on this criterion (no observation to backfill).

Pipeline:
    1. Run migrate_rubrics_to_crebo to rewrite Rubric.criteria
       (idempotent — only updates rubrics still carrying legacy shapes).
    2. Remap GradingSession.ai_draft_scores keys (8 -> 6, average on merge).
    3. Remap GradingSession.final_scores keys (same logic).
    4. Delete SkillObservations linked to the 8 English Skill rows
       (they'll be regenerated from the migrated scores).
    5. Delete SkillMetric rows for the 8 English slugs
       (they'll be regenerated by recompute).
    6. Delete the 8 English Skill rows themselves so the radar /
       per-criterium widgets stop showing zero-data duplicate spokes.
    7. Re-run bind_rubric_to_observations on every session with scores.
    8. Run recompute_skill_metrics_from_observations to rebuild Bayesian
       SkillMetric scores from the new observations.

Idempotent. Re-running on already-migrated data is a no-op (rubrics
already on Crebo shape skip step 1; sessions with no English keys in
their score maps skip step 2-3; English Skill rows already deleted
skip step 4-6; the rebind + recompute are idempotent by design).

Safety:
    - Wraps the whole DB-touching portion in transaction.atomic().
    - Single dry-run flag reports what would change without writing.
    - Leaves a [CREBO_MERGE] evidence string on merged scores so the
      audit trail records the data shape change.

Usage:
    python manage.py migrate_data_to_crebo --dry-run
    python manage.py migrate_data_to_crebo
    python manage.py migrate_data_to_crebo --user afriqxpress@gmail.com
"""
from __future__ import annotations

import logging
from typing import Any

from django.core.management import call_command
from django.core.management.base import BaseCommand
from django.db import transaction

logger = logging.getLogger(__name__)


# Old 8-criterion English -> Crebo 6-criterion Dutch.
# Order matters for "base" identification when two old slugs map to one
# new one: the earlier entry is treated as the base (its score wins on
# tie-break), the later entry is folded in (averaged).
SLUG_MAP: dict[str, str] = {
    "security":       "veiligheid",
    "validation":     "veiligheid",
    "code_quality":   "code_kwaliteit",
    "best_practices": "code_kwaliteit",
    "architecture":   "code_ontwerp",
    "testing":        "testen",
    "performance":    "verbetering",
    "documentation":  "verbetering",
}

# Old slugs we'll delete after migration so the radar widgets stop
# showing zero-data duplicate spokes alongside the canonical Crebo ones.
OLD_SLUGS: frozenset[str] = frozenset(SLUG_MAP.keys())


def remap_scores(scores: dict) -> tuple[dict, list[str]]:
    """
    Remap a GradingSession.ai_draft_scores or .final_scores dict from
    8-English keys to 6-Crebo keys. When two old keys collide on the
    same new key, average their scores and stamp the evidence string.

    Returns:
        (new_scores, changed_keys) — the migrated dict, and a list of
        old keys that were rewritten. An empty changed_keys list means
        the input was already on Crebo shape (or used unrelated slugs).
    """
    if not scores:
        return scores or {}, []

    new_scores: dict[str, Any] = {}
    changed_keys: list[str] = []

    for old_key, detail in scores.items():
        new_key = SLUG_MAP.get(old_key, old_key)
        if new_key != old_key:
            changed_keys.append(old_key)

        # Normalize to {"score": int, "evidence": str} shape regardless
        # of whether the source was a bare int or a dict.
        if isinstance(detail, dict):
            new_score = detail.get("score")
            new_evidence = detail.get("evidence", "")
        else:
            new_score = detail
            new_evidence = ""

        if new_key in new_scores:
            # Merge: average the two scores. Picks integer floor on .5
            # to keep values in the 1-4 rubric scale.
            existing = new_scores[new_key]
            old_score = existing.get("score") if isinstance(existing, dict) else existing
            old_evidence = existing.get("evidence", "") if isinstance(existing, dict) else ""

            try:
                avg_score = round((float(old_score) + float(new_score)) / 2.0)
            except (TypeError, ValueError):
                # Fall back to the existing score on bad data.
                avg_score = old_score

            merged_evidence = (old_evidence + " | " + new_evidence).strip(" |") or "[CREBO_MERGE]"
            new_scores[new_key] = {
                "score": avg_score,
                "evidence": f"[CREBO_MERGE] {merged_evidence}"[:1000],
            }
        else:
            new_scores[new_key] = (
                {"score": new_score, "evidence": new_evidence}
                if (new_evidence or new_key != old_key)
                else detail
            )

    return new_scores, changed_keys


class Command(BaseCommand):
    help = (
        "Consolidate the 8-criterion English rubric data shape into the "
        "Crebo 25604 6-criterion Dutch shape. Migrates GradingSession "
        "scores, SkillObservations, and SkillMetrics. Idempotent."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Report what would change without writing.",
        )
        parser.add_argument(
            "--user",
            help=(
                "Restrict migration to one student (by email). Default: all "
                "users. Useful for smoke-testing on a single demo account "
                "before a full run."
            ),
        )

    def handle(self, *args, **opts):
        from grading.models import GradingSession
        from skills.models import Skill, SkillMetric, SkillObservation

        dry = opts["dry_run"]
        user_email = opts.get("user")

        # ── Step 1. Rubric migration ─────────────────────────────────────
        self.stdout.write(self.style.HTTP_INFO("\n[1/8] Rubric.criteria migration"))
        if dry:
            call_command("migrate_rubrics_to_crebo", "--dry-run")
        else:
            call_command("migrate_rubrics_to_crebo")

        # ── Step 2-3. Remap GradingSession scores ────────────────────────
        self.stdout.write(self.style.HTTP_INFO(
            "\n[2-3/8] GradingSession ai_draft_scores + final_scores remap"
        ))
        sessions = GradingSession.objects.all()
        if user_email:
            sessions = sessions.filter(submission__student__email=user_email)

        sessions_touched = 0
        keys_rewritten = 0
        for session in sessions.iterator():
            new_draft, changed_draft = remap_scores(session.ai_draft_scores or {})
            new_final, changed_final = remap_scores(session.final_scores or {})
            if not changed_draft and not changed_final:
                continue

            sessions_touched += 1
            keys_rewritten += len(changed_draft) + len(changed_final)

            if dry:
                self.stdout.write(
                    f"  [dry-run] session #{session.id} "
                    f"draft_keys={changed_draft} final_keys={changed_final}"
                )
                continue

            with transaction.atomic():
                fields = []
                if changed_draft:
                    session.ai_draft_scores = new_draft
                    fields.append("ai_draft_scores")
                if changed_final:
                    session.final_scores = new_final
                    fields.append("final_scores")
                if fields:
                    session.save(update_fields=fields)

        self.stdout.write(
            f"  Sessions touched: {sessions_touched}, keys rewritten: {keys_rewritten}"
        )

        # ── Step 4-5-6. Delete observations + metrics + skills for old slugs ─
        self.stdout.write(self.style.HTTP_INFO(
            "\n[4-6/8] Delete legacy English Skill rows + their observations + metrics"
        ))

        obs_qs = SkillObservation.objects.filter(skill__slug__in=OLD_SLUGS)
        metrics_qs = SkillMetric.objects.filter(skill__slug__in=OLD_SLUGS)
        skills_qs = Skill.objects.filter(slug__in=OLD_SLUGS)

        if user_email:
            obs_qs = obs_qs.filter(user__email=user_email)
            metrics_qs = metrics_qs.filter(user__email=user_email)
            # Skills are global — if scoping to one user, leave Skill rows
            # alone to avoid breaking other users' data.
            skills_to_delete = 0
        else:
            skills_to_delete = skills_qs.count()

        obs_count = obs_qs.count()
        metric_count = metrics_qs.count()

        self.stdout.write(
            f"  Observations to delete: {obs_count}, "
            f"Metrics to delete: {metric_count}, "
            f"Skills to delete: {skills_to_delete}"
        )

        if not dry:
            with transaction.atomic():
                obs_qs.delete()
                metrics_qs.delete()
                if not user_email:
                    skills_qs.delete()

        # ── Step 7. Re-bind every session with migrated scores ───────────
        self.stdout.write(self.style.HTTP_INFO(
            "\n[7/8] Re-bind SkillObservations from migrated scores"
        ))
        if dry:
            count = sessions.exclude(ai_draft_scores={}).exclude(
                ai_draft_scores__isnull=True,
            ).count()
            self.stdout.write(f"  [dry-run] would re-bind {count} sessions")
        else:
            from grading.services.skill_binding import bind_rubric_to_observations
            rebound = 0
            obs_total = 0
            for session in sessions.exclude(ai_draft_scores={}).exclude(
                ai_draft_scores__isnull=True,
            ).iterator():
                # prefer_final if the docent has actually edited the rubric
                # in the UI before sending; otherwise use the AI draft.
                prefer_final = bool(session.final_scores or {})
                try:
                    n = bind_rubric_to_observations(session, prefer_final=prefer_final)
                    rebound += 1
                    obs_total += n
                except Exception as e:  # noqa: BLE001
                    self.stderr.write(
                        f"  session #{session.id} bind FAILED: {e}"
                    )
            self.stdout.write(
                f"  Re-bound {rebound} sessions, created/updated {obs_total} observations"
            )

        # ── Step 8. Recompute SkillMetrics from observations ─────────────
        self.stdout.write(self.style.HTTP_INFO(
            "\n[8/8] Recompute SkillMetrics from migrated observations"
        ))
        if dry:
            self.stdout.write("  [dry-run] would call recompute_skill_metrics_from_observations")
        else:
            args = ["--allow-prod"]
            if user_email:
                args = ["--user", user_email] + args
            call_command("recompute_skill_metrics_from_observations", *args)

        self.stdout.write(self.style.SUCCESS(
            f"\nDone{' (dry-run, no writes)' if dry else ''}."
        ))
