# Generated by Django 6.0.3 on 2026-04-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_finding', 'New Finding'), ('skill_improvement', 'Skill Improvement'), ('weekly_summary', 'Weekly Summary'), ('team_update', 'Team Update')], default='new_finding', max_length=50),
        ),
    ]
