# Generated by Django 6.0.3 on 2026-03-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=40)),
                ('commit_message', models.TextField(blank=True)),
                ('commit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('branch', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('files_changed', models.PositiveIntegerField(default=0)),
                ('lines_added', models.PositiveIntegerField(default=0)),
                ('lines_removed', models.PositiveIntegerField(default=0)),
                ('overall_score', models.FloatField(blank=True, help_text='Overall code quality score (0-100)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('llm_model', models.CharField(blank=True, help_text='Model used for evaluation', max_length=50)),
                ('llm_tokens_used', models.PositiveIntegerField(default=0)),
                ('processing_ms', models.PositiveIntegerField(default=0, help_text='Processing time in milliseconds')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('suggestion', 'Suggestion')], default='warning', max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('line_start', models.PositiveIntegerField()),
                ('line_end', models.PositiveIntegerField()),
                ('original_code', models.TextField(help_text='The problematic code')),
                ('suggested_code', models.TextField(blank=True, help_text='Suggested fix')),
                ('explanation', models.TextField(blank=True, help_text='Why this is better')),
                ('is_fixed', models.BooleanField(default=False)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('fixed_in_commit', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'findings',
                'ordering': ['-evaluation__created_at', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='FindingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_score', models.FloatField(default=5.0, help_text='Points deducted from skill score')),
            ],
            options={
                'db_table': 'finding_skills',
            },
        ),
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(help_text='Pattern type that triggers this recommendation', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_url', models.URLField(blank=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('book', 'Book'), ('course', 'Course'), ('documentation', 'Documentation')], default='article', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_recommendations',
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(help_text='Type of recurring issue', max_length=100)),
                ('pattern_key', models.CharField(help_text='Unique key for this pattern', max_length=200)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Number of occurrences')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patterns',
            },
        ),
    ]
