# Generated by Django 6.0.3 on 2026-03-27 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('projects', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Matched user (if found)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='finding',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='findingskill',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_skills', to='evaluations.finding'),
        ),
        migrations.AddField(
            model_name='findingskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_skills', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='finding',
            name='skills',
            field=models.ManyToManyField(related_name='findings', through='evaluations.FindingSkill', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='learningrecommendation',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional: project-specific pattern', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='projects.project'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='sample_findings',
            field=models.ManyToManyField(blank=True, related_name='patterns', to='evaluations.finding'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['project', 'created_at'], name='evaluations_project_254b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['commit_sha'], name='evaluations_commit__1ebdf6_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['author_email'], name='evaluations_author__a9197e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='findingskill',
            unique_together={('finding', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='pattern',
            unique_together={('user', 'project', 'pattern_key')},
        ),
    ]
