# Generated by Django 6.0.3 on 2026-03-30 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_target_github_and_batch_job'),
        ('evaluations', '0003_evaluation_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='batch_job',
            field=models.ForeignKey(blank=True, help_text='Set when this evaluation was produced by a batch run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='batch.batchjob'),
        ),
    ]
