# Generated by Django 6.0.3 on 2026-03-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_target_github_and_batch_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='author_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
