# Generated by Django 6.0.3 on 2026-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_author_email_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='developer_explanation',
            field=models.TextField(blank=True, help_text="Developer's explanation of why the original code was wrong"),
        ),
        migrations.AddField(
            model_name='finding',
            name='understanding_feedback',
            field=models.TextField(blank=True, help_text="LLM feedback on the developer's explanation"),
        ),
        migrations.AddField(
            model_name='finding',
            name='understanding_level',
            field=models.CharField(blank=True, choices=[('got_it', 'Got It'), ('partial', 'Partial'), ('not_yet', 'Not Yet')], help_text='LLM-assessed understanding level', max_length=20),
        ),
    ]
