# Generated by Django 5.2.12 on 2026-04-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_fix_and_learn_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='prompt_version',
            field=models.CharField(blank=True, help_text='Hash/version of the LLM prompt used for this evaluation', max_length=32),
        ),
    ]
