/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Exact Stitch color palette
        background: '#10141a',
        'primary-container': '#58a6ff',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-surface-variant': '#c0c7d4',
        outline: '#8b919d',
        'on-secondary-container': '#9db7dd',
        'on-primary': '#00315c',
        'inverse-on-surface': '#2d3137',
        'secondary-fixed': '#d3e4ff',
        'primary-fixed-dim': '#a2c9ff',
        'surface-bright': '#353940',
        'on-secondary': '#163151',
        'surface-variant': '#31353c',
        'tertiary-container': '#da9600',
        'on-background': '#dfe2eb',
        'inverse-surface': '#dfe2eb',
        'primary-fixed': '#d3e4ff',
        'on-tertiary-container': '#4f3400',
        'surface-container': '#1c2026',
        surface: '#10141a',
        tertiary: '#ffba42',
        'surface-container-highest': '#31353c',
        'surface-dim': '#10141a',
        'tertiary-fixed-dim': '#ffba42',
        'surface-container-lowest': '#0a0e14',
        error: '#ffb4ab',
        'secondary-container': '#2e4869',
        'on-secondary-fixed-variant': '#2e4869',
        'on-error-container': '#ffdad6',
        'surface-tint': '#a2c9ff',
        'on-surface': '#dfe2eb',
        'secondary-fixed-dim': '#aec8ef',
        'inverse-primary': '#0060aa',
        'tertiary-fixed': '#ffddaf',
        'on-tertiary-fixed': '#281800',
        'surface-container-high': '#262a31',
        'on-secondary-fixed': '#001c38',
        secondary: '#aec8ef',
        'outline-variant': '#414752',
        'on-primary-container': '#003a6b',
        primary: '#a2c9ff',
        'surface-container-low': '#181c22',
        'on-tertiary': '#432c00',
        'on-primary-fixed-variant': '#004882',
        'on-tertiary-fixed-variant': '#614000',
        'on-primary-fixed': '#001c38',
      },
      fontFamily: {
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Fira Code', 'Consolas', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
