# Generated by Django 6.0.3 on 2026-04-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0007_production_hardening'),
        ('users', '0012_add_teacher_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_template', models.BooleanField(default=False, help_text='True for built-in crebo 25187/25188 templates shipped with the product.')),
                ('name', models.CharField(max_length=150)),
                ('criteria', models.JSONField(default=list, help_text='List of criterion dicts. Validated at save time.')),
                ('calibration', models.JSONField(blank=True, default=dict, help_text='Docent voice calibration (tone, language, depth, example_comments).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, help_text='Org that owns the rubric. Null for global templates (is_template=True).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='users.organization')),
                ('owner', models.ForeignKey(blank=True, help_text='Teacher/docent who created this rubric. Null for built-in templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rubrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grading_rubrics',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending (draft not yet requested)'), ('drafting', 'Drafting (AI running)'), ('drafted', 'Draft ready'), ('reviewing', 'Docent reviewing'), ('sending', 'Sending comments'), ('posted', 'All comments posted'), ('partial', 'Partial post (needs Resume)'), ('failed', 'Draft generation failed'), ('discarded', 'Draft discarded (student pushed new code)')], default='pending', max_length=20)),
                ('ai_draft_scores', models.JSONField(blank=True, default=dict, help_text='Per-criterion: {criterion_id: {"score": int, "evidence": "quote from diff"}}')),
                ('ai_draft_comments', models.JSONField(blank=True, default=list, help_text='List of {"file", "line", "body", "client_mutation_id"} comments.')),
                ('ai_draft_model', models.CharField(blank=True, max_length=80)),
                ('ai_draft_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_draft_truncated', models.BooleanField(default=False, help_text='True if diff was truncated before being sent to the LLM (>3000 lines).')),
                ('final_scores', models.JSONField(blank=True, default=dict)),
                ('final_comments', models.JSONField(blank=True, default=list)),
                ('final_summary', models.TextField(blank=True)),
                ('docent_review_started_at', models.DateTimeField(blank=True, null=True)),
                ('docent_review_time_seconds', models.IntegerField(blank=True, help_text='Stopwatch metric: time from open to send. THE core v1 validation metric.', null=True)),
                ('sending_started_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('partial_post_error', models.JSONField(blank=True, help_text='{"error_class", "message", "failed_at_comment_idx"} when state=partial', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sessions', to='users.organization')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_sessions', to='grading.rubric')),
            ],
            options={
                'db_table': 'grading_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source_control_type', models.CharField(choices=[('github_org', 'GitHub (personal or org repos)'), ('gitlab', 'GitLab (personal or group repos)')], default='github_org', max_length=20)),
                ('target_branch_pattern', models.CharField(default='main', help_text='Branch(es) to grade. Supports "main" or "main,develop" or "*" (all).', max_length=100)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='users.organization')),
                ('owner', models.ForeignKey(help_text='Primary docent. Must have role=TEACHER.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_classes', to=settings.AUTH_USER_MODEL)),
                ('secondary_docent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_classes', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_using', to='grading.rubric')),
            ],
            options={
                'verbose_name_plural': 'classes',
                'db_table': 'grading_classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_in_draft', models.BooleanField(default=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_session_links', to='evaluations.evaluation')),
                ('grading_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_evaluations', to='grading.gradingsession')),
            ],
            options={
                'db_table': 'grading_session_evaluations',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(max_length=200)),
                ('pr_number', models.IntegerField()),
                ('pr_url', models.URLField()),
                ('pr_title', models.CharField(blank=True, max_length=500)),
                ('base_branch', models.CharField(default='main', max_length=100)),
                ('head_branch', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open (student may still push)'), ('submitted', 'Submitted for grading'), ('graded', 'Graded and closed')], default='open', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(db_column='classroomid', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grading.classroom')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_submissions', to='users.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grading_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_session', to='grading.submission'),
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=20)),
                ('delivery_id', models.CharField(help_text='X-GitHub-Delivery header or GitLab equivalent.', max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grading_webhook_deliveries',
                'indexes': [models.Index(fields=['received_at'], name='grading_web_receive_17d4f2_idx')],
                'unique_together': {('provider', 'delivery_id')},
            },
        ),
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_repo_url', models.URLField(blank=True, help_text="Student's chosen repo URL for this class (e.g., github.com/jandeboer/assignment-q3).", null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroommemberships', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(db_column='classroomid', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='grading.classroom')),
            ],
            options={
                'db_table': 'grading_classroommemberships',
                'ordering': ['classroom', 'student'],
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.CreateModel(
            name='LLMCostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('cheap', 'Cheap tier (on-commit)'), ('premium', 'Premium tier (docent grading)')], max_length=20)),
                ('model_name', models.CharField(max_length=80)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_eur', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('ceiling_rejected', models.BooleanField(default=False, help_text='True if ai_engine rejected this call due to hard per-docent daily ceiling.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, db_column='classroomid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_cost_logs', to='grading.classroom')),
                ('docent', models.ForeignKey(blank=True, help_text='Null for cheap-tier background evals (no docent in the loop).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_cost_logs', to=settings.AUTH_USER_MODEL)),
                ('grading_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_cost_logs', to='grading.gradingsession')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_cost_logs', to='users.organization')),
            ],
            options={
                'db_table': 'grading_llm_cost_logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['docent', 'occurred_at'], name='grading_llm_docent__4a3d1c_idx'), models.Index(fields=['classroom', 'occurred_at'], name='grading_llm_classro_b3c731_idx'), models.Index(fields=['tier', 'occurred_at'], name='grading_llm_tier_67b56a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mutation_id', models.CharField(help_text='Hash of (session_id, file, line, body_hash). Idempotency key.', max_length=64)),
                ('github_comment_id', models.BigIntegerField(blank=True, help_text='The numeric id GitHub returned on POST /pulls/comments.', null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField()),
                ('body_preview', models.CharField(blank=True, max_length=200)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('grading_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments', to='grading.gradingsession')),
            ],
            options={
                'db_table': 'grading_posted_comments',
                'indexes': [models.Index(fields=['grading_session', 'posted_at'], name='grading_pos_grading_006eae_idx')],
                'unique_together': {('grading_session', 'client_mutation_id')},
            },
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['org', 'is_template', '-updated_at'], name='grading_rub_org_id_051068_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['org', 'owner', '-created_at'], name='grading_cla_org_id_d893f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionevaluation',
            unique_together={('grading_session', 'evaluation')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['org', 'classroom', 'status'], name='grading_sub_org_id_2ca3dc_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', '-created_at'], name='grading_sub_student_760c8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('classroom', 'repo_full_name', 'pr_number')},
        ),
        migrations.AddIndex(
            model_name='gradingsession',
            index=models.Index(fields=['org', 'state', '-created_at'], name='grading_ses_org_id_08fe99_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingsession',
            index=models.Index(fields=['state', 'updated_at'], name='grading_ses_state_39eb77_idx'),
        ),
    ]
