# Generated by Django 6.0.3 on 2026-04-18 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassMembership',
            new_name='ClassroomMembership',
        ),
    ]
