# Generated by Django 6.0.3 on 2026-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_cohort_course_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Soft-archive timestamp. Archived cohorts stay queryable for history but are hidden by default in list views.', null=True),
        ),
        migrations.AddField(
            model_name='cohortmembership',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp. Row is preserved so historical grading sessions remain valid.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Soft-archive timestamp. Archived courses are hidden by default but preserved for grading history.', null=True),
        ),
    ]
