# Generated by Django 6.0.3 on 2026-04-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_primary_contributors(apps, schema_editor):
    """
    Workstream G backfill: for every existing Submission, create a
    SubmissionContributor row for its `student` with is_primary_author=True
    and contribution_fraction=1.0 so solo-repo history keeps working with
    per-contributor skill attribution.
    """
    Submission = apps.get_model("grading", "Submission")
    SubmissionContributor = apps.get_model("grading", "SubmissionContributor")
    for sub in Submission.objects.all().iterator():
        if sub.student_id is None:
            continue
        SubmissionContributor.objects.get_or_create(
            submission=sub,
            user_id=sub.student_id,
            defaults={
                "is_primary_author": True,
                "contribution_fraction": 1.0,
                "lines_changed": 0,
                "commits_count": 0,
            },
        )


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op: dropping the tables (handled by schema ops) removes the rows."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_cohort_archived_at_cohortmembership_removed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_changed', models.IntegerField(default=0, help_text="Total lines added+removed in this contributor's commits on the PR.")),
                ('commits_count', models.IntegerField(default=0)),
                ('contribution_fraction', models.FloatField(default=0.0, help_text='0.0-1.0, lines_changed / total_lines_changed across all contributors.')),
                ('is_primary_author', models.BooleanField(default=False, help_text='True for the PR author (Submission.student). False for co-contributors.')),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_links', to='grading.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grading_submission_contributors',
                'ordering': ['-is_primary_author', '-contribution_fraction', 'user_id'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='contributors',
            field=models.ManyToManyField(help_text="All students who contributed to this PR's shared repo. For solo repos, exactly one contributor (== student). For group projects (shared repo), the full cohort-member list. See Workstream G of Nakijken Copilot v1.", related_name='contributed_submissions', through='grading.SubmissionContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submissioncontributor',
            index=models.Index(fields=['user', '-attached_at'], name='grading_sub_user_id_1ef656_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissioncontributor',
            constraint=models.UniqueConstraint(fields=('submission', 'user'), name='uniq_sub_contrib'),
        ),
        migrations.RunPython(backfill_primary_contributors, noop_reverse),
    ]
