# Generated by Django 6.0.3 on 2026-04-24 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_course_unique_teacher_per_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsession',
            name='iteration_number',
            field=models.PositiveIntegerField(default=1, help_text='1-based iteration counter for this PR. Increments on each new post-POSTED synchronize.'),
        ),
        migrations.AddField(
            model_name='gradingsession',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='If set, this session was replaced by a newer iteration when the student pushed new commits after the teacher sent feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='grading.gradingsession'),
        ),
        migrations.AlterField(
            model_name='gradingsession',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sessions', to='grading.submission'),
        ),
    ]
