# Generated by Django 6.0.3 on 2026-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_iteration_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsession',
            name='partial_post_error',
            field=models.JSONField(blank=True, help_text='{"stage", "error_class", "message", ...} populated on every FAILED, PARTIAL, and DISCARDED transition. See model source for the full shape.', null=True),
        ),
    ]
