# Generated by Django 6.0.3 on 2026-04-28 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_alter_gradingsession_partial_post_error'),
        ('users', '0012_add_teacher_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcostlog',
            name='prompt_version',
            field=models.CharField(blank=True, default='', help_text="Hash or semantic version of the prompt template used for this LLM call (e.g. 'rubric_grader_v3', 'ai_drafter_2026_04_28'). Lets ops compare cost and quality across prompt iterations without backfilling. Empty for callers that don't pass it; populated incrementally as services adopt the field.", max_length=64),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='Soft-archive timestamp. Archived projects are hidden by default but preserved for grading history.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='grading.course')),
                ('created_by', models.ForeignKey(help_text='The teacher who created this project. Stored for audit; not used for permissions. Related-name is grading-namespaced because the legacy projects.Project model already claims `created_projects`.', on_delete=django.db.models.deletion.PROTECT, related_name='created_grading_projects', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(help_text='Denormalized from course.cohort.org so OrgScopedManager can filter by a single FK at the ORM level. Set automatically on save() — see save() override below.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.organization')),
                ('rubric', models.ForeignKey(blank=True, help_text="Override the course's rubric for this project. NULL means 'inherit from course.rubric'. Useful when a single course has an early-semester rubric (forgiving) and a late-semester rubric (strict) for different assignments.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_using', to='grading.rubric')),
            ],
            options={
                'db_table': 'grading_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Assignment this PR belongs to (Cohort → Course → Project). Nullable so submissions ingested before the Project layer existed (or via legacy CohortMembership.student_repo_url matching) keep working.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='grading.project'),
        ),
        migrations.CreateModel(
            name='StudentProjectRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True, help_text='Full repo URL (e.g., https://github.com/jandeboer/assignment-q3). Used by the webhook router to match incoming PRs to this project + student.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(help_text='Denormalized from project.org for OrgScopedManager.', on_delete=django.db.models.deletion.CASCADE, related_name='student_project_repos', to='users.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_repos', to='grading.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grading_student_project_repos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['course', 'archived_at', '-created_at'], name='grading_pro_course__1ed717_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['org', '-created_at'], name='grading_pro_org_id_4c616c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprojectrepo',
            index=models.Index(fields=['repo_url'], name='grading_stu_repo_ur_89f029_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprojectrepo',
            index=models.Index(fields=['student', '-updated_at'], name='grading_stu_student_4a09a9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprojectrepo',
            index=models.Index(fields=['project', '-updated_at'], name='grading_stu_project_d53986_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprojectrepo',
            constraint=models.UniqueConstraint(fields=('project', 'student'), name='uniq_student_project_repo'),
        ),
    ]
