# Generated by Django 6.0.3 on 2026-03-29 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(help_text='GitHub repository URL')),
                ('branch', models.CharField(default='main', help_text='Branch to analyze', max_length=100)),
                ('target_email', models.EmailField(blank=True, help_text='Filter commits by author email (empty = all)', max_length=254)),
                ('max_commits', models.PositiveIntegerField(default=500, help_text='Maximum commits to process')),
                ('since_date', models.DateField(blank=True, help_text='Only process commits after this date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning Repository'), ('analyzing', 'Analyzing Commits'), ('building_profile', 'Building Profile'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_commits', models.PositiveIntegerField(default=0)),
                ('processed_commits', models.PositiveIntegerField(default=0)),
                ('skipped_commits', models.PositiveIntegerField(default=0, help_text='Commits skipped (merge commits, too small, etc.)')),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('skills_detected', models.JSONField(default=list, help_text='List of skill IDs detected')),
                ('patterns_detected', models.JSONField(default=list, help_text='List of pattern types detected')),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, help_text='Optional: link to existing project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchCommitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=40)),
                ('commit_message', models.TextField()),
                ('commit_date', models.DateTimeField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('files_changed', models.PositiveIntegerField(default=0)),
                ('lines_added', models.PositiveIntegerField(default=0)),
                ('lines_removed', models.PositiveIntegerField(default=0)),
                ('overall_score', models.FloatField(blank=True, help_text='Code quality score (0-100)', null=True)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('skills_snapshot', models.JSONField(default=dict, help_text='Skill scores at this commit: {skill_id: score}')),
                ('patterns_snapshot', models.JSONField(default=list, help_text='Patterns detected in this commit')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_results', to='batch.batchjob')),
            ],
            options={
                'db_table': 'batch_commit_results',
                'ordering': ['commit_date'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('intermediate', 'Intermediate'), ('senior', 'Senior'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('overall_score', models.FloatField(default=50.0, help_text='Overall coding proficiency (0-100)')),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('new', 'New User')], default='new', max_length=20)),
                ('strengths', models.JSONField(default=list, help_text='List of skill IDs where user excels')),
                ('weaknesses', models.JSONField(default=list, help_text='List of skill IDs needing improvement')),
                ('top_patterns', models.JSONField(default=list, help_text='Most frequent issue patterns')),
                ('resolved_patterns', models.JSONField(default=list, help_text='Patterns user has overcome')),
                ('commits_analyzed', models.PositiveIntegerField(default=0)),
                ('total_findings', models.PositiveIntegerField(default=0)),
                ('total_fixes', models.PositiveIntegerField(default=0)),
                ('first_commit_date', models.DateField(blank=True, null=True)),
                ('last_commit_date', models.DateField(blank=True, null=True)),
                ('score_history', models.JSONField(default=list, help_text='List of {date, score} for tracking progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_job', models.ForeignKey(blank=True, help_text='Batch job that created/updated this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='batch.batchjob')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'developer_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['user', 'status'], name='batch_jobs_user_id_a8e405_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['created_at'], name='batch_jobs_created_9b19c3_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcommitresult',
            index=models.Index(fields=['job', 'commit_date'], name='batch_commi_job_id_1acd99_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcommitresult',
            index=models.Index(fields=['commit_sha'], name='batch_commi_commit__d535be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchcommitresult',
            unique_together={('job', 'commit_sha')},
        ),
    ]
