# Generated by Django 6.0.3 on 2026-03-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchjob',
            name='target_email',
        ),
        migrations.AddField(
            model_name='batchjob',
            name='target_github_username',
            field=models.CharField(blank=True, help_text='Filter commits by author (passed to git log --author); empty = all commits', max_length=150),
        ),
    ]
