# Generated by Django 6.0.3 on 2026-03-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_target_github_and_batch_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='resolved_branches',
            field=models.JSONField(blank=True, default=list, help_text='Branches the worker will process (set on create; from GitHub + optional author filter)'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='branch',
            field=models.CharField(default='main', help_text='Branch to analyze, or "__all__" to process every active branch', max_length=100),
        ),
    ]
