# Generated by Django 5.2.12 on 2026-04-15 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_resolved_branches'),
        ('projects', '0003_repo_url_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional: link to existing project', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_jobs', to='projects.project'),
        ),
    ]
