# Generated by Django 6.0.3 on 2026-03-27 01:23

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], default='github', max_length=20)),
                ('repo_url', models.URLField(help_text='Full repository URL')),
                ('repo_owner', models.CharField(help_text='Owner/organization name', max_length=100)),
                ('repo_name', models.CharField(help_text='Repository name', max_length=100)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('webhook_secret', models.CharField(default=projects.models.generate_webhook_secret, max_length=64)),
                ('webhook_active', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('developer', 'Developer'), ('viewer', 'Viewer')], default='developer', max_length=20)),
                ('git_email', models.EmailField(blank=True, help_text='Git commit email (if different from user email)', max_length=254, null=True)),
                ('git_username', models.CharField(blank=True, help_text='Git username (if different from user)', max_length=100, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_members',
            },
        ),
    ]
