# Generated by Django 6.0.3 on 2026-03-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, help_text='Full repository URL (empty until linked by a developer)', null=True),
        ),
    ]
