# Generated by Django 6.0.3 on 2026-03-27 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'db_table': 'skill_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('weight', models.FloatField(default=1.0, help_text='Weight for scoring calculations')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillcategory')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=100.0, help_text='Current skill score (0-100)')),
                ('issue_count', models.PositiveIntegerField(default=0, help_text='Total issues found for this skill')),
                ('fixed_count', models.PositiveIntegerField(default=0, help_text='Total issues fixed for this skill')),
                ('trend', models.CharField(choices=[('up', 'Improving'), ('down', 'Declining'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('previous_score', models.FloatField(blank=True, null=True)),
                ('first_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_metrics', to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_metrics',
            },
        ),
    ]
