# Generated by Django 5.2.12 on 2026-04-15 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_repo_url_optional'),
        ('skills', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='skillmetric',
            index=models.Index(fields=['user', 'project'], name='skill_metri_user_id_c01059_idx'),
        ),
        migrations.AddIndex(
            model_name='skillmetric',
            index=models.Index(fields=['skill', 'project'], name='skill_metri_skill_i_9dc151_idx'),
        ),
        migrations.AddIndex(
            model_name='skillmetric',
            index=models.Index(fields=['user', 'score'], name='skill_metri_user_id_1e489a_idx'),
        ),
    ]
