# Generated by Django 6.0.3 on 2026-04-16 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_production_hardening'),
        ('projects', '0003_repo_url_optional'),
        ('skills', '0003_production_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmetric',
            name='bayesian_score',
            field=models.FloatField(default=50.0, help_text='Bayesian skill score (0-100). Starts at 50 (uncertain).'),
        ),
        migrations.AddField(
            model_name='skillmetric',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Confidence in the score (0.0-1.0). Grows with observations.'),
        ),
        migrations.AddField(
            model_name='skillmetric',
            name='observation_count',
            field=models.PositiveIntegerField(default=0, help_text='Total SkillObservation records for this skill.'),
        ),
        migrations.AddField(
            model_name='skillmetric',
            name='proven_concepts',
            field=models.PositiveIntegerField(default=0, help_text='Fix & Learn concepts proven by future behavior.'),
        ),
        migrations.AddField(
            model_name='skillmetric',
            name='relapsed_concepts',
            field=models.PositiveIntegerField(default=0, help_text='Fix & Learn concepts where developer relapsed.'),
        ),
        migrations.AlterField(
            model_name='skillmetric',
            name='score',
            field=models.FloatField(default=100.0, help_text='Legacy skill score (0-100). Use bayesian_score instead.'),
        ),
        migrations.CreateModel(
            name='GrowthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the snapshot week')),
                ('avg_weighted_score', models.FloatField(default=0)),
                ('avg_complexity', models.FloatField(default=0)),
                ('evaluation_count', models.PositiveIntegerField(default=0)),
                ('pct_critical', models.FloatField(default=0)),
                ('pct_warning', models.FloatField(default=0)),
                ('pct_info', models.FloatField(default=0)),
                ('pct_suggestion', models.FloatField(default=0)),
                ('patterns_resolved', models.PositiveIntegerField(default=0)),
                ('patterns_relapsed', models.PositiveIntegerField(default=0)),
                ('concepts_proven', models.PositiveIntegerField(default=0)),
                ('concepts_relapsed', models.PositiveIntegerField(default=0)),
                ('new_skills_touched', models.PositiveIntegerField(default=0)),
                ('growth_velocity', models.FloatField(default=0, help_text='Score change rate vs. previous week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, help_text='null = cross-project snapshot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_snapshots', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'growth_snapshots',
                'indexes': [models.Index(fields=['user', 'week_start'], name='growth_snap_user_id_79e93d_idx')],
                'unique_together': {('user', 'project', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='LearningProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(help_text="Pattern key, e.g. 'bare_except', 'sql_injection'", max_length=200)),
                ('taught_at', models.DateTimeField()),
                ('understanding_level', models.CharField(help_text='got_it / partial / not_yet from Fix & Learn', max_length=20)),
                ('concept_summary', models.TextField(blank=True, help_text='What was explained to the developer')),
                ('status', models.CharField(choices=[('taught', 'Taught'), ('pending', 'Pending Proof'), ('proven', 'Proven'), ('reinforced', 'Reinforced'), ('relapsed', 'Relapsed')], default='taught', max_length=20)),
                ('proof_evidence_count', models.PositiveIntegerField(default=0, help_text='Commits where similar code handled correctly')),
                ('proof_commit', models.CharField(blank=True, help_text='Commit SHA that proved understanding', max_length=40)),
                ('proven_at', models.DateTimeField(blank=True, null=True)),
                ('relapse_commit', models.CharField(blank=True, help_text='Commit SHA where mistake was repeated', max_length=40)),
                ('relapsed_at', models.DateTimeField(blank=True, null=True)),
                ('score_impact_applied', models.FloatField(default=0, help_text='Total score impact applied from this proof')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_proofs', to='evaluations.finding')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_proofs', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_proofs',
                'indexes': [models.Index(fields=['user', 'status'], name='learning_pr_user_id_1004a7_idx'), models.Index(fields=['user', 'skill', 'issue_type'], name='learning_pr_user_id_d660a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=40)),
                ('quality_score', models.FloatField(help_text='Raw LLM score for this skill (0-100)')),
                ('complexity_weight', models.FloatField(default=0.7, help_text='From CommitClassifier: simple=0.4, medium=0.7, complex=1.0')),
                ('weighted_score', models.FloatField(help_text='quality_score × complexity_weight')),
                ('lines_changed', models.PositiveIntegerField(default=0)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('suggestion_count', models.PositiveIntegerField(default=0)),
                ('issue_density', models.FloatField(default=0, help_text='weighted_issues / max(lines_changed, 10)')),
                ('decision_appropriate', models.PositiveIntegerField(default=0)),
                ('decision_suboptimal', models.PositiveIntegerField(default=0)),
                ('decision_poor', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_observations', to='evaluations.evaluation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_observations', to='projects.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_observations',
                'indexes': [models.Index(fields=['user', 'skill', 'created_at'], name='skill_obser_user_id_d897d1_idx'), models.Index(fields=['user', 'project', 'created_at'], name='skill_obser_user_id_bbd5c7_idx'), models.Index(fields=['evaluation'], name='skill_obser_evaluat_a3282c_idx')],
            },
        ),
    ]
