# Generated by Django 6.0.3 on 2026-03-28 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboard_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OnboardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboard_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboard_codes',
                'indexes': [models.Index(fields=['user', 'code'], name='onboard_cod_user_id_0020af_idx')],
            },
        ),
    ]
