# Generated by Django 6.0.3 on 2026-04-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_onboard_completed_onboardcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dev_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dev_profile_data',
            field=models.JSONField(blank=True, default=dict, help_text='Developer profile questionnaire answers'),
        ),
    ]
