# Generated by Django 6.0.3 on 2026-03-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_llmconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='git_provider',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'BitBucket')], help_text='Which host you use for code (must match project provider for auto-match)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='git_provider_email',
            field=models.EmailField(blank=True, help_text='Email in your git commits (if different from ReviewHub email)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='git_provider_username',
            field=models.CharField(blank=True, help_text='Login on GitHub / GitLab / Bitbucket (matches push sender on webhooks)', max_length=100, null=True),
        ),
    ]
