# Generated by Django 6.0.3 on 2026-03-29 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_legacy_git_fields(apps, schema_editor):
    User = apps.get_model('users', 'User')
    GitProviderConnection = apps.get_model('users', 'GitProviderConnection')
    for u in User.objects.exclude(git_provider__isnull=True).exclude(git_provider=''):
        un = (u.git_provider_username or '').strip()
        if not un:
            un = (u.username or 'linked')[:100]
        em = u.git_provider_email or None
        GitProviderConnection.objects.get_or_create(
            user_id=u.pk,
            provider=u.git_provider,
            username=un[:100],
            defaults={'email': em},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_git_provider_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=20)),
                ('username', models.CharField(help_text='Login on the host (matches push sender on webhooks)', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Optional: git commit author email if different from ReviewHub email', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'git_provider_connections',
                'ordering': ['provider', 'username'],
                'unique_together': {('user', 'provider', 'username')},
            },
        ),
        migrations.RunPython(copy_legacy_git_fields, migrations.RunPython.noop),
        migrations.RemoveField(model_name='user', name='git_provider'),
        migrations.RemoveField(model_name='user', name='git_provider_email'),
        migrations.RemoveField(model_name='user', name='git_provider_username'),
    ]
