# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_llmconfiguration_auth_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_github_personal_access_token',
            field=models.BinaryField(
                blank=True,
                db_column='github_personal_access_token',
                help_text='Encrypted GitHub PAT for private repo API access (batch branch list)',
                null=True,
            ),
        ),
    ]
