# Generated by Django 5.2.12 on 2026-04-01 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_github_personal_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('mobile', 'Mobile Developer'), ('other', 'Other')], max_length=30)),
                ('experience_years', models.FloatField()),
                ('primary_language', models.CharField(max_length=50)),
                ('other_languages', models.JSONField(blank=True, default=list)),
                ('self_scores', models.JSONField(default=dict, help_text='{"clean_code": 4, "testing": 2, …} — 1 (weak) to 5 (strong)')),
                ('focus_first', models.CharField(blank=True, choices=[('making_it_work', 'Making it work'), ('code_quality', 'Code quality'), ('performance', 'Performance'), ('readability', 'Readability')], max_length=30)),
                ('writes_tests', models.CharField(blank=True, choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never')], max_length=20)),
                ('edge_case_handling', models.CharField(blank=True, choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely')], max_length=20)),
                ('debugging_approach', models.CharField(blank=True, choices=[('trial_and_error', 'Trial and error'), ('logs_tracing', 'Logs and tracing'), ('structured', 'Structured debugging'), ('struggle', 'I struggle with debugging')], max_length=30)),
                ('can_design_system', models.CharField(blank=True, choices=[('yes', 'Yes confidently'), ('with_help', 'With help'), ('no', 'No')], max_length=20)),
                ('comfortable_with', models.JSONField(blank=True, default=list)),
                ('worked_on', models.JSONField(blank=True, default=list)),
                ('enjoy_most', models.CharField(blank=True, choices=[('frontend_ui', 'Frontend UI'), ('backend_logic', 'Backend logic'), ('system_design', 'System design'), ('devops', 'DevOps'), ('data_ai', 'Data / AI')], max_length=30)),
                ('want_to_improve', models.CharField(blank=True, choices=[('clean_code', 'Clean code'), ('architecture', 'Architecture'), ('testing', 'Testing'), ('debugging', 'Debugging'), ('performance', 'Performance')], max_length=30)),
                ('current_goal', models.CharField(blank=True, choices=[('get_job', 'Get a job'), ('improve_job', 'Improve at current job'), ('become_senior', 'Become senior'), ('learn_new_tech', 'Learn new tech'), ('build_startup', 'Build a startup')], max_length=30)),
                ('learning_style', models.CharField(blank=True, choices=[('short_tips', 'Short tips'), ('detailed', 'Detailed explanations'), ('examples', 'Examples / projects'), ('challenges', 'Challenges')], max_length=20)),
                ('proud_code', models.TextField(blank=True)),
                ('struggled_code', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dev_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dev_profiles',
            },
        ),
    ]
