# Generated by Django 5.2.12 on 2026-04-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dev_profile_completed_user_dev_profile_data'),
        ('users', '0009_userdevprofile'),
    ]

    operations = [
    ]
