# Generated by Django 6.0.3 on 2026-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_organization_and_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('developer', 'Developer'), ('viewer', 'Viewer')], default='developer', max_length=20),
        ),
    ]
